### ISSUE TITLE
Pair is Distributive

### ISSUE THREAD

**Issue by paf31** [sharkdp/purescript-pairs#1]
There is a valid instance of `Distributive` from `purescript-distributive` which can be added. I can send a PR if you like.

**Comment by sharkdp** [comment]
I have no idea how you found out about this library so quickly, but thanks! :smile: 

I didn't know about `Distributive`, so this was a nice exercise. There are no laws stated for `Distributive`, so I hope this is okay.

I was wondering why I couldn't find a datatype such as `Pair`, neither in PureScript, nor in Haskell... do you know about something similar? It seems to be useful for some purposes..

The `Bind`/`Monad` instance feels rather weird because it discards some values ... I kind of guessed it by considering types, symmetry considerations and the laws. I'm not sure if it is really useful or used anywhere else..

Edit: Random side note: I guess `Pair a` is isomorphic to `NonEmpty Identity a`

**Comment by paf31** [comment]
> I have no idea how you found out about this library so quickly, but thanks!

I'm working on a library to search for new PureScript libraries on GitHub, so I tend to have the search open 😄 

In Haskell, there is `uniform-pair`. `Pair` is a `Bind`/`Monad` since it's a `Reader` - in many ways actually, one for any valid `Semigroup`/`Monoid` on `Boolean`. Whether that's the one you want, I don't know. it probably isn't compatible with the zippy `Applicative` instance though.

`Distributive` is a Haskell 98 approximation to `Representable`, i.e. Naperian functors. Among other things, it lets us define a nifty optic called a grate (`cotraverse :: Grate (Pair a) (Pair b) a b`), which has a natural zippy operation. You can compose these like you can compose lenses and prisms, and they're useful for lifting certain operations over Naperian functors.

**Comment by sharkdp** [comment]
> In Haskell, there is uniform-pair. Pair is a Bind/Monad since it's a Reader - in many ways actually, one for any valid Semigroup/Monoid on Boolean. Whether that's the one you want, I don't know. it probably isn't compatible with the zippy Applicative instance though.

That's a very interesting connection. In case anyone else is reading this in the future, there is an interesting blog post about this at http://comonad.com/reader/2013/representing-applicatives/. It also says something about the `Monad` instance:

> And, unfortunately, that this monad instance is typically fairly useless (in that it is also "zippy" -- i.e. the monad instance on a pair just acts on the two elements pointwise, without ever allowing anything in the first slot to affect anything in the second slot, etc.). 

I think this is exactly what I meant by "feels rather weird ..." :smile: 

> Distributive is a Haskell 98 approximation to Representable, i.e. Naperian functors. Among other things, it lets us define a nifty optic called a grate (cotraverse :: Grate (Pair a) (Pair b) a b), which has a natural zippy operation. You can compose these like you can compose lenses and prisms, and they're useful for lifting certain operations over Naperian functors.

Not sure if I understood anything, but that also sounds interesting. I'll try to read something about this...

Thanks for the detailed answer!

**Comment by paf31** [comment]
This is heavy reading, but the important bit for this discussion is "van Laarhoven grates": http://r6research.livejournal.com/28050.html

_Edit_: incidentally, that post also gives the `Distributive` laws - `cotraverse` is a lawful grate whenever

```
cotraverse runIdentity = runIdentity
cotraverse (g <<< fmap f <<< getCompose) = cotraverse g <<< fmap (cotraverse f) <<< getCompose
```
